export {default as Logo} from './logo.svg';
export {default as NameLogo} from './name_logo.svg';
export {default as MobileNameLogo} from './mobile_name_logo.svg';
export {default as Polygon} from './polygon.svg';
export {default as BurgerIcon} from './burger_menu.svg';
export {default as Mail} from './mail.svg';
export {default as CloseIcon} from './close.svg';
export {default as SupportMailIcon} from './support_mail.svg';
export {default as SupportCallIcon} from './support_call.svg';